### ISSUE TITLE
Story::ความคืบหน้า1

### ISSUE THREAD

**Issue by BallballTH** [BallballTH/Tom-Khai#1]

**Comment by Mathilbzel** [comment]
https://www.figma.com/file/jH0IGbOce2EEAk0eCDhCHA/Khaitom?type=whiteboard&node-id=0-1&t=2SA5rDNskhzwxL0D-0

**Comment by faiinrd** [comment]
เนื้อเรื่องแบบบรรยาย
https://docs.google.com/document/d/1zIwnJAMZlFJqMX784WO4O-1C00H_rj4bf1g5dpwSe00/edit?usp=sharing
